In [100]:
pip install numpy

In [101]:
import numpy as np

In [102]:
#0D array
arr_0d=np.array(2)
print(arr_0d)

2


In [103]:
#1D array
arr_1d=np.array([1,2,3])
print(arr_1d)

[1 2 3]


In [104]:
#2D array
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [105]:
#3D array
arr_3d=np.array([[[5,10],[15,20]],[[25,30],[35,40]]])
print(arr_3d)


[[[ 5 10]
  [15 20]]

 [[25 30]
  [35 40]]]


In [106]:
print(arr_0d.ndim)
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

0
1
2
3


In [107]:
#Array of zeros
zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [108]:
#Array of ones
ones=np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [109]:
#Array of random values
random_arr=np.random.random((2,3))
print(random_arr)

[[0.44655574 0.05828552 0.47553125]
 [0.64604411 0.55934393 0.50820758]]


In [110]:
#Identity matrix
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [111]:
#Array with a range of values
range_arr=np.arange(0,10,2)
print(range_arr)

[0 2 4 6 8]


In [112]:
#Array attributes
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data type:",arr.dtype)
print("Number of dimensions:",arr.ndim)


Shape: (2, 3)
Size: 6
Data type: int64
Number of dimensions: 2


You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.
Each greenhouse has sensors that record temperature (°C) readings at different times of the day.


Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.

In [113]:
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data)

[[22 25 20]
 [24 26 23]]


Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.

In [114]:

print("Shape:",temp_data.shape)
print("Size:",temp_data.size)
print("Data type:",temp_data.dtype)
print("Number of dimensions:",temp_data.ndim)

Shape: (2, 3)
Size: 6
Data type: int64
Number of dimensions: 2


Add a third greenhouse

The third greenhouse (GH3) records [21, 23, 22].

In [115]:
#GH3 array
arr_gh3=np.array([21,23,22])
print(arr_gh3)


[21 23 22]


Create a new array updated_temp_data that includes all three greenhouses.

In [116]:
updated_temp_data=np.array([[[22,25,20],[24,26,23],[21,23,22]]])
print(updated_temp_data)

[[[22 25 20]
  [24 26 23]
  [21 23 22]]]


Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).

Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.

In [117]:
sensor_error_flags=np.zeros((2,3))
print(sensor_error_flags)

greenhouse_identity=np.eye(3)
print(greenhouse_identity)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Display all arrays

Print updated_temp_data, sensor_error_flags, and greenhouse_identity.

In [118]:
print("Updated temp data:",updated_temp_data)
print("Sensor error flags:",sensor_error_flags)
print("Greenhouse identity:",greenhouse_identity)

Updated temp data: [[[22 25 20]
  [24 26 23]
  [21 23 22]]]
Sensor error flags: [[0. 0. 0.]
 [0. 0. 0.]]
Greenhouse identity: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [119]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
print(arr[1,-1])

2
6


In [120]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[:,1:])

[[2 3]
 [5 6]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).

1.Create the 2D NumPy array
Create an array named shipments using the above data.

In [121]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,65,70,75]])
print(shipments)

[[50 60 55 70 65 80 90]
 [40 45 50 60 65 70 75]]


Access single elements (Indexing):

Get the number of Apples shipped on Wednesday

In [122]:
print(shipments[0,2])

55


Get the number of Oranges shipped on Sunday.

In [123]:
print(shipments[1,6])

75


Access multiple elements (Slicing):

Extract all the weekday shipments (Mon–Fri) for all fruits.

In [124]:
#slicing
print(shipments[:,0:5])

[[50 60 55 70 65]
 [40 45 50 60 65]]


Extract only the weekend shipments (Sat & Sun).

In [125]:
print(shipments[:,5:7])

[[80 90]
 [70 75]]


Extract the shipments of Apples from Wednesday to Saturday.

In [126]:
print(shipments[0:1,2:6])

[[55 70 65 80]]


Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.

In [127]:
shipments[0,5]=100
print(shipments)

[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  65  70  75]]


ARRAY OPERATIONS

In [128]:
a=np.array([10,20,30])
b=np.array([15,25,30])
print(a+b)
print(a*b)
#scalar operation
print(a*2)

[25 45 60]
[150 500 900]
[20 40 60]


MATRIX MULTIPLICATION

In [129]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[4,5],[6,7]])
mul=np.dot(mat1,mat2)
print(mul)


[[16 19]
 [36 43]]


BROADCASTING

In [130]:
a=np.array([10,20,30])
b=5
print(a+b)

[15 25 35]


UNIVERSAL FUNCTIONS

In [131]:
arr1=np.array([11,12,13])

#Exponentiation
print(np.exp(arr1))

#square root
print(np.sqrt(arr1))

#Logarithm
print(np.log(arr1))


[ 59874.1417152  162754.791419   442413.39200892]
[3.31662479 3.46410162 3.60555128]
[2.39789527 2.48490665 2.56494936]


In [132]:
#1. Arithmetic ufuncs
x=np.array([1,2,3])
y=np.array([4,5,6])
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))
print(np.power(x, y))
print(np.mod(x, y))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[1 2 3]


In [133]:
#trignometric ufuncs
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))
print(np.degrees(x))
print(np.radians(x))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]
[1.57079633        nan        nan]
[ 0. nan nan]
[0.78539816 1.10714872 1.24904577]
[ 57.29577951 114.59155903 171.88733854]
[0.01745329 0.03490659 0.05235988]


/tmp/ipython-input-1625070732.py:5: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(x))
/tmp/ipython-input-1625070732.py:6: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(x))


In [134]:
#Rounding ufuncs
print(np.round(x))
print(np.floor(x))
print(np.ceil(x))
print(np.trunc(x))

[1 2 3]
[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]


In [135]:
#statistical ufuncs
print(np.min(x))
print(np.max(x))
print(np.mean(x))
print(np.std(x))
print(np.var(x))
print(np.sum(x))
print(np.prod(x))

1
3
2.0
0.816496580927726
0.6666666666666666
6
6


In [136]:
#logical ufuncs
print(np.logical_and(x, y))
print(np.logical_or(x, y))
print(np.logical_not(x))
print(np.logical_xor(x,y))

[ True  True  True]
[ True  True  True]
[False False False]
[False False False]


In [137]:
#comparision ufuncs
print(np.greater(x, y))
print(np.less(x, y))
print(np.equal(x, y))
print(np.not_equal(x, y))
print(np.greater_equal(x, y))
print(np.less_equal(x, y))

[False False False]
[ True  True  True]
[False False False]
[ True  True  True]
[False False False]
[ True  True  True]


In [138]:
#bitwise ufuncs
print(np.bitwise_and(x, y))
print(np.bitwise_or(x, y))
print(np.bitwise_xor(x, y))
print(np.invert(x))

[0 0 2]
[5 7 7]
[5 7 5]
[-2 -3 -4]


You are a data engineer at a renewable-energy company that runs 3 solar farms.
Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):

Create arrays

Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).

In [139]:
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])

Stack them into a single 3D array production_all of shape (3, 4, 3).

In [140]:
production_all=np.stack([farmA,farmB,farmC])
print(production_all)

[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]


Array attributes

Print the .shape, .size, .dtype, and .ndim of production_all.

In [141]:
print("Shape:",production_all.shape)
print("Size:",production_all.size)
print("Data type:",production_all.dtype)
print("Number of dimensions:",production_all.ndim)

Shape: (3, 4, 3)
Size: 36
Data type: int64
Number of dimensions: 3


Per-farm totals (arithmetic & aggregation)

Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).

In [142]:
total_per_farm=np.sum(production_all,axis=(1,2))
print(total_per_farm)

[126 234 174]


Compute mean, std, and var per farm.

In [143]:
mean_per_farm=np.mean(production_all,axis=(1,2))
print(mean_per_farm)

std_per_farm=np.std(production_all,axis=(1,2))
print(std_per_farm)

var_per_farm=np.var(production_all,axis=(1,2))
print(var_per_farm)

[10.5 19.5 14.5]
[1.97905701 1.97905701 1.97905701]
[3.91666667 3.91666667 3.91666667]


Per-hour matrix multiplication idea (matrix op)

For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).

In [144]:
hour_weights=np.array([0.5,1.0,0.75])

Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)

In [145]:
weighted_per_panel1=np.dot(farmA,hour_weights)
print(weighted_per_panel1)

weighted_per_panel2=np.dot(farmB,hour_weights)
print(weighted_per_panel2)

weighted_per_panel3=np.dot(farmC,hour_weights)
print(weighted_per_panel3)


[25.25 23.   29.5  17.75]
[44.75 43.25 49.75 38.5 ]
[34.   31.25 38.5  26.75]


Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually)

In [146]:
production_all=production_all.astype(float)
production_all[1]+=0.5
print(production_all)

[[[10.  12.  11. ]
  [ 9.  11.  10. ]
  [12.  13.  14. ]
  [ 8.   7.   9. ]]

 [[20.5 19.5 21.5]
  [18.5 20.5 19.5]
  [22.5 23.5 21.5]
  [17.5 18.5 16.5]]

 [[15.  16.  14. ]
  [14.  13.  15. ]
  [16.  17.  18. ]
  [12.  11.  13. ]]]


Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.

In [147]:
norm=(production_all-mean_per_farm)/std_per_farm
print(norm.shape)

(3, 4, 3)


Apply many ufuncs (use the ufuncs listed previously)
Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:

In [148]:
exp_ = np.exp(norm)
expm1_ = np.expm1(norm)
log_ = np.log(np.abs(norm) + 1)
log10_ = np.log10(np.abs(norm) + 1)
log2_ = np.log2(np.abs(norm) + 1)

sin_ = np.sin(norm)
cos_ = np.cos(norm)
tan_ = np.tan(norm)
arcsin_ = np.arcsin(np.clip(sin_, -1, 1))
arccos_ = np.arccos(np.clip(cos_, -1, 1))
arctan_ = np.arctan(norm)

deg_ = np.degrees(arctan_)
rad_ = np.radians(deg_)

round_ = np.round(norm, 2)
floor_ = np.floor(norm)
ceil_ = np.ceil(norm)
trunc_ = np.trunc(norm)

print("\nExp summary:", exp_.shape, exp_.dtype)
print("Sin mean:", np.mean(sin_))
print("Log sum:", np.sum(log_))

#Comparison & logical masks
high_output = production_all > 20
even_hours_mask = np.array([False, True, False])
even_hours_mask = np.broadcast_to(even_hours_mask, production_all.shape)

and_mask = np.logical_and(high_output, even_hours_mask)
or_mask = np.logical_or(high_output, even_hours_mask)
not_mask = np.logical_not(high_output)
xor_mask = np.logical_xor(high_output, even_hours_mask)

greater_equal_mask = np.greater_equal(production_all, 18)
less_mask = np.less(production_all, 12)

print("\nHigh output mask shape:", high_output.shape)
print("Number of high outputs:", np.sum(high_output))

# Bitwise operations
alerts = np.array([
    [[1,0,1],
     [0,0,1],
     [1,1,0],
     [0,1,0]]
] * 3, dtype=np.int32)

bit_and = np.bitwise_and(alerts, alerts)
bit_or = np.bitwise_or(alerts, np.invert(alerts))
bit_not = np.invert(alerts)

print("\nBitwise AND sample:\n", bit_and[0])

#Arithmetic ufuncs again
add_ = np.add(norm, 2)
sub_ = np.subtract(norm, 1)
mul_ = np.multiply(norm, 3)
div_ = np.divide(norm, 2)
power_ = np.power(norm, 2)
mod_ = np.mod(norm, 1)

print("\nArithmetic (add/sub/mul/div) sample:", add_[0,0,:])

# Aggregation examples
sum_exp = np.sum(np.exp(norm))
mean_sin = np.mean(np.sin(norm))
print("\nSum of exp(norm):", sum_exp)
print("Mean of sin(norm):", mean_sin)


Exp summary: (3, 4, 3) float64
Sin mean: -0.013830623420671602
Log sum: 37.487834475797186

High output mask shape: (3, 4, 3)
Number of high outputs: 6

Bitwise AND sample:
 [[1 0 1]
 [0 0 1]
 [1 1 0]
 [0 1 0]]

Arithmetic (add/sub/mul/div) sample: [ 1.74735442 -1.78968364  0.23148097]

Sum of exp(norm): 820.0362759214044
Mean of sin(norm): -0.013830623420671602


Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.

In [149]:
panel_totals_per_farm = np.sum(production_all, axis=2)   # sum across hours → shape (3,4)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)

print("\nPanel totals per farm:\n", panel_totals_per_farm)
print("Needs maintenance:", needs_maintenance)


Panel totals per farm:
 [[33.  30.  39.  24. ]
 [61.5 58.5 67.5 52.5]
 [45.  42.  51.  36. ]]
Needs maintenance: [ True False  True]


Final KPIs (aggregation)

In [150]:
overall_total = np.sum(production_all)
peak_value = np.max(production_all)
peak_index = np.unravel_index(np.argmax(production_all), production_all.shape)
average_per_panel = np.mean(production_all, axis=(0,2))  # across farms & hours

print("\nOverall total energy:", overall_total)
print("Peak production value:", peak_value)
print("Peak location (farm, panel, hour):", peak_index)
print("Average per panel across farms:", average_per_panel)


Overall total energy: 540.0
Peak production value: 23.5
Peak location (farm, panel, hour): (np.int64(1), np.int64(2), np.int64(1))
Average per panel across farms: [15.5 14.5 17.5 12.5]


RESHAPING ARRAYS

In [151]:
a=np.array([1,2,3,4,5,6])
reshaped=a.reshape(2,3)
print(reshaped)

reshaped1=a.reshape(3,2)
print(reshaped1)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


STACKING

In [152]:
a=np.array([1,2])
b=np.array([3,4])
#vertical stack
print(np.vstack((a,b)))
#horizontal stack
print(np.hstack((a,b)))

[[1 2]
 [3 4]]
[1 2 3 4]


SPLITTING

In [153]:
a1=np.array([1,2,3,4,5,6])
print(np.array_split(a1,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


ADVANCED INDEXING

In [154]:
#Boolean indexing
arr=np.array([1,2,3,4,5])
print(arr[arr>3])

#Fancy indexing
arr=np.array([10,20,30,40])
indices=[0,2]
print(arr[indices])


[4 5]
[10 30]


COPY VS VIEW

In [157]:
#view shares memory
arr=np.array([1,2,3])
view=arr.view()
view[0]=10
print(arr)
#copy does not share memory
copy=arr.copy()
copy[0]=10
print(arr)

[10  2  3]
[10  2  3]


SAVING AND LOADING

In [158]:
#saving to a file
arr=np.array([1,2,3])
np.save('array.npy',arr)

#loading from a file
loaded_arr=np.load('array.npy')
print(loaded_arr)

[1 2 3]


TasksArray Creation

Create a 1D array of numbers from 10 to 50.

In [162]:
arr1=np.arange(10,51,1)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Create a 3x3 array of random numbers between 0 and 1.

In [165]:
arr2=np.random.random((3,3))
print(arr2)

[[0.49014792 0.21105098 0.31412666]
 [0.17800107 0.88882972 0.88302515]
 [0.74338332 0.66195364 0.24826253]]


Array Attributes
Find the shape, size, and data type of the array you created in the previous task.

In [166]:
print("Shape:",arr1.shape)
print("Size:",arr1.size)
print("Data type:",arr1.dtype)
print("Number of dimensions:",arr1.ndim)

print("Shape:",arr2.shape)
print("Size:",arr2.size)
print("Data type:",arr2.dtype)
print("Number of dimensions:",arr2.ndim)



Shape: (41,)
Size: 41
Data type: int64
Number of dimensions: 1
Shape: (3, 3)
Size: 9
Data type: float64
Number of dimensions: 2


Basic Operations

Add 5 to every element of a 1D array.

Multiply two 2D arrays element-wise.

In [168]:
b=5
print(arr1+b)

b1=np.array([[1,2,3],[4,5,6]])
b2=np.array([[4,5,6],[6,7,8]])
res=b1*b2
print(res)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[ 4 10 18]
 [24 35 48]]


Indexing and Slicing

Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.

A subarray of the first three rows and first two columns.

In [183]:
a3=np.arange(1,26).reshape(5,5)
print(a3)

print(a3[0,:])
print(a3[:,4:5])

subarr=a3[0:3,0:2]
print(subarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[[ 5]
 [10]
 [15]
 [20]
 [25]]
[[ 1  2]
 [ 6  7]
 [11 12]]


Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.

In [190]:
arr=np.random.randint(10,101,size=10)
print(arr)

print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.std(arr))

[82 41 91 85 53 45 68 67 45 16]
91
16
59.3
22.302690420664497


Reshaping

Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.

In [191]:
a=np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Broadcasting

Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.

In [193]:
a3=np.ones((3,3))
print(a3)
a1=np.array([1,2,3])
print(a3+a1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


Filtering

Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.

In [195]:
a2=np.arange(1,51)
print(a2)
print(a2[a2%5==0])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[ 5 10 15 20 25 30 35 40 45 50]


Matrix

Create two 2x2 matrices and perform matrix multiplication.

In [196]:
c1=np.array([[1,2],[4,5]])
c2=np.array([[4,5],[7,8]])
matmul=np.dot(c1,c2)
print(matmul)

[[18 21]
 [51 60]]


Advanced Indexing

Given a 4x4 array, use fancy indexing to extract the diagonal elements

In [198]:
a4=np.arange(1,17).reshape(4,4)
print(a4)

print(a4[[0,1,2,3],[0,1,2,3]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  6 11 16]
